### ISSUE TITLE
Enter/Return key ImGui remap

### ISSUE THREAD

**Issue by andras-v** [napframework/nap#14]
Hey,
https://github.com/napframework/nap/blob/04801e6d49d2476a88abb2907d091675eca01b7c/modules/napimgui/src/imguiservice.cpp#L389
Isn't this supposed to be
```c++
io.KeyMap[ImGuiKey_Enter] = (int)EKeyCode::KEY_RETURN;
```
?

**Comment by cklosters** [comment]
Hi, I think you're correct. According to [SDL](https://wiki.libsdl.org/SDL_Keycode):

`"Return" (the Enter key (main keyboard))`

Since `ImGui` doesn't distinguish between the return and enter key, the default enter should be the return key.

Feel free to submit a PR, otherwise I'll update it for the next release.

**Comment by cklosters** [comment]
Merged: https://github.com/napframework/nap/pull/15 

Please open another issue if the problem you mentioned is related to our implementation of ImGUI.
