### ISSUE TITLE
Duplicating nap::StructBuffer breaks on assert

### ISSUE THREAD

**Issue by lshoek** [napframework/nap#30]
Can be reproduced in `helloworld` demo project

- Create a `nap::StructBuffer`
- Duplicate the buffer (right-click, then duplicate)
- Assert fail on `document.cpp:1153` followed by crash

```
assert(src_value.get_type().is_wrapper() && src_value.get_type().get_wrapped_type().is_pointer());
```

**Comment by cklosters** [comment]
Well, the assert is right here: it encounters an embedded object that isn't a pointer to a resource, which shouldn't exist. The current definition of `nap::StructBuffer` is wrong - the description should not be flagged as embedded because it's a copyable struct. See: https://github.com/napframework/nap/commit/92b3f6d1d7c24d9d3f9c825d1ca2a63dc285bc5f
